-- MySQL Script generated by MySQL Workbench
-- Qua 11 Nov 2015 03:24:36 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gdsw_matricula
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gdsw_matricula` ;

-- -----------------------------------------------------
-- Schema gdsw_matricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gdsw_matricula` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gdsw_matricula` ;

-- -----------------------------------------------------
-- Table `gdsw_matricula`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`curso` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`curso` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `aulas_por_dia` INT NULL,
  `dias_por_semana` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdsw_matricula`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`disciplina` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `periodo` INT NULL,
  `sigla` VARCHAR(45) NULL,
  `ativa` TINYINT(1) NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC),
  INDEX `fk_curso_idx` (`curso_id` ASC),
  CONSTRAINT `fk_curso_id`
    FOREIGN KEY (`curso_id`)
    REFERENCES `gdsw_matricula`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdsw_matricula`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`horario` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`horario` (
  `disciplina_id` INT NOT NULL,
  `aula` INT NOT NULL COMMENT 'Inteiro indicando a aula da semana, segundo o padrão do curso.',
  PRIMARY KEY (`disciplina_id`),
  CONSTRAINT `fk_horario_disciplina`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `gdsw_matricula`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdsw_matricula`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`category` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `gdsw_matricula`.`disciplinas_has_disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`disciplinas_has_disciplinas` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`disciplinas_has_disciplinas` (
  `disciplinas_id` INT NOT NULL,
  `disciplinas_cursos_id` INT NOT NULL,
  `disciplinas_id1` INT NOT NULL,
  `disciplinas_cursos_id1` INT NOT NULL,
  PRIMARY KEY (`disciplinas_id`, `disciplinas_cursos_id`, `disciplinas_id1`, `disciplinas_cursos_id1`),
  INDEX `fk_disciplinas_has_disciplinas_disciplinas2_idx` (`disciplinas_id1` ASC, `disciplinas_cursos_id1` ASC),
  INDEX `fk_disciplinas_has_disciplinas_disciplinas1_idx` (`disciplinas_id` ASC, `disciplinas_cursos_id` ASC),
  CONSTRAINT `fk_disciplinas_has_disciplinas_disciplinas1`
    FOREIGN KEY (`disciplinas_id` , `disciplinas_cursos_id`)
    REFERENCES `gdsw_matricula`.`disciplina` (`id` , `curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplinas_has_disciplinas_disciplinas2`
    FOREIGN KEY (`disciplinas_id1` , `disciplinas_cursos_id1`)
    REFERENCES `gdsw_matricula`.`disciplina` (`id` , `curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gdsw_matricula`.`dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdsw_matricula`.`dependencia` ;

CREATE TABLE IF NOT EXISTS `gdsw_matricula`.`dependencia` (
  `disciplina_id` INT NOT NULL,
  `requisito_id` INT NOT NULL,
  PRIMARY KEY (`disciplina_id`, `requisito_id`),
  INDEX `fk_requisito_idx` (`requisito_id` ASC),
  INDEX `fk_disciplina_idx` (`disciplina_id` ASC),
  CONSTRAINT `fk_disciplinas_has_disciplinas1_disciplinas1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `gdsw_matricula`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplinas_has_disciplinas1_disciplinas2`
    FOREIGN KEY (`requisito_id`)
    REFERENCES `gdsw_matricula`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
